@echo off
cd backend
echo Installing dependencies...
call npm install
echo Generating Prisma Client...
set DATABASE_URL=file:./dev.db
call npx prisma generate
echo Migrating Database...
call npx prisma migrate dev --name init
echo Seeding Database...
call npx ts-node src/scripts/seed_and_verify.ts
echo Starting Backend Server...
call npm run dev
pause
